version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8080:8000"
    volumes:
      - ./static:/app/static
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "4", "--threads", "4", "--access-logfile", "-"]
